package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"regexp"
	"strings"

	"github.com/grafana/gcx/cmd/gcx/root"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func main() {
	version := flag.String("version", "", "Release tag")
	configPath := flag.String("config", "", "Generated configuration reference")
	envPath := flag.String("env", "", "Generated environment variable reference")
	output := flag.String("output", "", "Output Markdown file")
	flag.Parse()
	if *version == "" || *configPath == "" || *envPath == "" || *output == "" {
		log.Fatal("version, config, env and output are required")
	}
	configDoc, err := os.ReadFile(*configPath)
	if err != nil {
		log.Fatal(err)
	}
	envDoc, err := os.ReadFile(*envPath)
	if err != nil {
		log.Fatal(err)
	}
	guide, err := os.ReadFile("docs/design/environment-variables.md")
	if err != nil {
		log.Fatal(err)
	}
	if err := os.Setenv("GCX_AGENT_MODE", "false"); err != nil {
		log.Fatal(err)
	}
	// Cobra captures the executable name when it constructs completion help.
	os.Args[0] = "gcx"
	page := render(root.Command(*version), *version, string(configDoc), supplementEnvironment(string(envDoc), string(guide)))
	if err := os.WriteFile(*output, []byte(page), 0600); err != nil {
		log.Fatal(err)
	}
}

func anchor(cmd *cobra.Command) string {
	return strings.ReplaceAll(cmd.CommandPath(), " ", "-")
}

func render(rootCmd *cobra.Command, version, configDoc, envDoc string) string {
	var out strings.Builder
	fmt.Fprintf(&out, `---
title: CLI reference
description: Complete gcx command, flag, environment variable, and configuration reference.
weight: 60
---

<!-- Generated by scripts/generate-cli-reference.sh. Edit command help or source metadata, not this page. -->

This reference describes gcx **%s**. Run `+"`gcx version`"+` to check your installed version.

Flag defaults below are for human mode. Agent mode changes defaults such as output format; explicit flags override those defaults.

- [Commands](#commands)
- [Environment variables](#environment-variables)
- [Configuration](#configuration)

## Commands

`, version)
	renderCommands(&out, rootCmd)
	out.WriteString("## Environment variables\n\n")
	envDoc = strings.ReplaceAll(envDoc, "\n## `", "\n### `")
	out.WriteString(withoutTitle(envDoc))
	out.WriteString("\n\n## Configuration\n\n")
	out.WriteString("The following schema describes configuration fields and their types. See [Configuration](../configuration/) for setup examples.\n\n")
	out.WriteString(withoutTitle(configDoc))
	out.WriteString("\n")

	// Time-dependent defaults otherwise change on every release-docs retry.
	dateDefault := regexp.MustCompile(`\(default "\d{4}-\d{2}-\d{2}"\)`)
	return dateDefault.ReplaceAllString(out.String(), `(default "YYYY-MM-DD")`)
}

func renderCommands(out *strings.Builder, cmd *cobra.Command) {
	if cmd.Hidden {
		return
	}
	cmd.InitDefaultHelpFlag()
	fmt.Fprintf(out, "### `%s` {#%s}\n\n", cmd.CommandPath(), anchor(cmd))
	description := cmd.Long
	if description == "" {
		description = cmd.Short
	}
	out.WriteString(strings.TrimSpace(description) + "\n\n")
	if cmd.Deprecated != "" {
		fmt.Fprintf(out, "**Deprecated:** %s\n\n", cmd.Deprecated)
	}
	if len(cmd.Aliases) > 0 {
		fmt.Fprintf(out, "**Aliases:** `%s`\n\n", strings.Join(cmd.Aliases, "`, `"))
	}
	if cmd.Runnable() {
		fmt.Fprintf(out, "```shell\n%s\n```\n\n", cmd.UseLine())
	}
	if cmd.Example != "" {
		fmt.Fprintf(out, "**Examples**\n\n```shell\n%s\n```\n\n", strings.TrimSpace(cmd.Example))
	}
	if flags := cmd.LocalNonPersistentFlags().FlagUsages(); flags != "" {
		fmt.Fprintf(out, "**Flags**\n\n```text\n%s```\n\n", flags)
	}
	if flags := cmd.PersistentFlags().FlagUsages(); flags != "" {
		fmt.Fprintf(out, "#### Shared flags {#%s-flags}\n\n```text\n%s```\n\n", anchor(cmd), flags)
	}
	inherited := cmd.InheritedFlags()
	for parent := cmd.Parent(); parent != nil; parent = parent.Parent() {
		var names []string
		parent.PersistentFlags().VisitAll(func(f *pflag.Flag) {
			if !f.Hidden && inherited.Lookup(f.Name) == f {
				names = append(names, "`--"+f.Name+"`")
			}
		})
		if len(names) > 0 {
			fmt.Fprintf(out, "Inherits %s from [`%s`](#%s-flags).\n\n", strings.Join(names, ", "), parent.CommandPath(), anchor(parent))
		}
	}
	for _, child := range cmd.Commands() {
		renderCommands(out, child)
	}
}

func withoutTitle(input string) string {
	_, body, _ := strings.Cut(strings.TrimSpace(input), "\n")
	return strings.TrimSpace(body)
}

// The guide also documents variables consumed outside the tagged config structs.
func supplementEnvironment(envDoc, guide string) string {
	var out strings.Builder
	out.WriteString(envDoc)
	seen := make(map[string]bool)
	for _, match := range regexp.MustCompile("## `([^`]+)`").FindAllStringSubmatch(envDoc, -1) {
		seen[match[1]] = true
	}
	for line := range strings.SplitSeq(guide, "\n") {
		columns := strings.Split(line, "|")
		if len(columns) != 5 || !strings.HasPrefix(strings.TrimSpace(columns[1]), "`") {
			continue
		}
		name := strings.Trim(strings.TrimSpace(columns[1]), "`")
		if seen[name] {
			continue
		}
		seen[name] = true
		description := strings.TrimSpace(columns[3])
		if strings.HasPrefix(name, "GRAFANA_PROVIDER_") {
			description = "Overrides the " + strings.TrimSpace(columns[2]) + " provider's " + description + " configuration."
		}
		// Repository-only design links have no equivalent on the public website.
		description = regexp.MustCompile(`\[([^]]+)\]\([^)]+\)`).ReplaceAllString(description, "$1")
		fmt.Fprintf(&out, "\n\n## `%s`\n\n%s\n", name, description)
	}
	return out.String()
}
